
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 8.8.2
      sourceRef:
        kind: HelmRepository
        name: grafana
  timeout: 5m
  releaseName: grafana
  values:
    annotations:
      reloader.stakater.com/auto: "true"

    service:
      ipFamilyPolicy: PreferDualStack

    admin:
      existingSecret: grafana-secrets
      userKey: ADMIN_USER
      passwordKey: ADMIN_PASSWORD

    sidecar:
      dashboard:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
      alerts:
        enabled: true
        searchNamespace: ALL

    grafana.ini:
      analytics:
        check_for_updates: true
      server:
        domain: iot.bricklou.ovh
        root_url: "https://%(domain)s/"

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources: []

    alerting:
      contactpoints.yaml:
        apiVersion: 1
        contactPoints:
          - orgId: 1
            name: &contact-receiver iot
            receivers: []
        policies.yaml:
          apiVersion: 1
          policies:
            - orgId: 1
              receiver: *contact-receiver
              group_by:
                - alertname

    plugins:
      - grafana-piechart-panel

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            allowUiUpdate: true
            options:
              path: /var/lib/grafana/dashboards

    dashboards:
      default: {}

    route:
      main:
        enabled: false
