---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  admin-user-password: "password"
  admin-user-token: "my-super-long-secret-token-1234567890"

  read-user-password: "password"
  write-user-password: "password"
  user-password: "password"
