---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: rabbitmq
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/rabbitmq
  ref:
    tag: 15.2.1

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  interval: 30m
  chartRef:
    name: rabbitmq
    kind: OCIRepository
  timeout: 5m
  values:
    replicaCount: 2

    commonAnnotations:
      reloader.stakater.com/auto: "true"

    persistence:
      size: 3Gi

    auth:
      existingPasswordSecret: rabbitmq-secrets
      existingSecretPasswordKey: ADMIN_PASSWORD

    extraPlugins: "rabbitmq_mqtt"

    extraConfiguration: |-
      mqtt.listeners.tcp.1 = 0.0.0.0:1883
      mqtt.exchange = amq.topic
      mqtt.vhost = /

    extraContainerPorts:
      - name: mqtt
        containerPort: 1883

    service:
      extraPorts:
        - name: mqtt
          port: 1883
          targetPort: 1883
