---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: rabbitmq
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/rabbitmq
  ref:
    tag: 15.2.1

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  interval: 30m
  chartRef:
    name: rabbitmq
    kind: OCIRepository
  timeout: 5m
  values:
    replicaCount: 2

    persistence:
      size: 3Gi

    auth:
      existingPasswordSecret: rabbitmq-secrets
      existingSecretPasswordKey: ADMIN_PASSWORD

    plugins: "rabbitmq_management rabbit_peer_discovery_k8s rabbitmq_mqtt"

    containerPorts:
      dist: 25672
      manager: 15672
      metrics: 9419
      mqtt: 1883
