---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: telegraf
spec:
  interval: 24h
  url: https://helm.influxdata.com/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: telegraf
spec:
  interval: 30m
  chart:
    spec:
      chart: telegraf
      version: 1.8.55
      sourceRef:
        kind: HelmRepository
        name: telegraf
  timeout: 5m
  releaseName: telegraf
  values:
    replicaCount: 2

    envFromSecret: "telegraf-secrets"
    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      enabled: false

    config:
      agent:
        debug: true
      outputs:
        - influxdb_v2:
            urls:
              - "http://influxdb:8086"
            token: "${INFLUXDB_TOKEN}"
            organization: "${INFLUXDB_ORG}"
            bucket: "${INFLUXDB_BUCKET}"
            namepass: ["iot"]

      inputs:
        - amqp_consumer:
            brokers: ["amqp://rabbitmq/"]
            exchange: "iot"
            queue: "iot"
            username: "${RABBITMQ_USER}"
            password: "${RABBITMQ_PASSWORD}"
            data_format: "json"
            json_time_key: "timestamp"

        #
        # - mqtt_consumer:
        #     servers: ["tcp://rabbitmq.project-iot.svc.cluster.local:1883"]
        #     username: "${RABBITMQ_USER}"
        #     password: "${RABBITMQ_PASSWORD}"
        #     topics: [
        #       "sensors/#",
        #     #  "devices/+/temperature"  # Example with MQTT wildcards
        #     ]
        #     # Connection configurations
        #     client_id: "telegraf_${HOSTNAME}"
        #     qos: 1
        #     # Data format configuration
        #     data_format: "json"  # or "value", "influx" depending on your message format
        #     # JSON parsing configuration (adjust based on your message structure)
        #     #json_string_fields: ["field1", "field2"]
        #     json_time_key: "timestamp"
        #     #json_tag_keys: ["device_id", "location"]
        #     #json_measurement_key: "measurement_name"
        #     # Optional: persist sessions
        #     persistent_session: true
        #
