---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: telegraf
spec:
  interval: 24h
  url: https://helm.influxdata.com/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: telegraf
spec:
  interval: 30m
  chart:
    spec:
      chart: telegraf
      version: 1.8.55
      sourceRef:
        kind: HelmRepository
        name: telegraf
  timeout: 5m
  releaseName: telegraf
  values:
    replicaCount: 2

    envFromSecret: "telegraf-secrets"
    podAnnotations:
      reloader.stakater.com/auto: "true"

    service:
      enabled: false

    config:
      agent:
        debug: true
      outputs:
        - influxdb_v2:
            urls:
              - "http://influxdb:8086"
            token: "${INFLUXDB_TOKEN}"
            organization: "${INFLUXDB_ORG}"
            bucket: "${INFLUXDB_BUCKET}"
            namepass: ["iot"]

      inputs:
        - amqp_consumer:
            brokers: ["amqp://rabbitmq/"]
            exchange: "iot"
            queue: "iot"
            username: "${RABBITMQ_USER}"
            password: "${RABBITMQ_PASSWORD}"
            data_format: "json"
            json_time_key: "timestamp"
            json_time_format: "unix"
