---
name: Kubernetes Lint

on:
  push:
    paths:
      - k8s/**
      - .github/workflows/kubernetes-lint.yaml
  pull_request:

jobs:
  kubernetes-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.6
        with:
          directory: k8s
